### ISSUE TITLE
fail to push- 

### ISSUE THREAD

**Issue by alblubaugh** [epid8060fall2019/Amanda_Blubaugh-project#2]
https://github.com/libgit2/libgit2sharp/issues/1528 

Here is a link with the issue I am having pushing my project: (cannot write chunk header) where people said if they waited and tried another time it worked? I have tried saving and closing R, Gitkraken and attempted repushing. Gitkraken attempts to push for quite a while before tripping the error.

**Comment by alblubaugh** [comment]
https://stackoverflow.com/questions/7986139/git-error-when-trying-to-push-pre-receive-hook-declined

The link above is another error I have gotten while trying to push things in smaller chunks.

**Comment by andreashandel** [comment]
I'm not sure what's going wrong. I saw something about big files being maybe the problem in those discussions, are you trying to push large (>100s of MB) files to GitHub? In cases like that, I generally recommend the 'restart' method. Move all your files out of the repository, delete it both locally and on GitHub, then create a new one and place your files back in there. See also here:
https://happygitwithr.com/burn.html

**Comment by alblubaugh** [comment]
Thank you for the suggestions; this was definitely the case. I am uploading everything in much smaller chunks now and it seems to be working. The .txt files are just too large.

**Comment by bevcope** [comment]
I have the same problem. I suppose I could push things in smaller chunks, but that's a work-around. A fix to the bug would be better, right?
